# Generated by Django 5.2.4 on 2025-09-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=12)),
                ('name', models.CharField(help_text='e.g., Common Stock', max_length=255)),
                ('authorized_shares', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('stakeholder_type', models.CharField(choices=[('FOUNDER', 'Founder'), ('INVESTOR', 'Investor'), ('EMPLOYEE', 'Employee')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=12)),
                ('date_issued', models.DateField()),
                ('number_of_shares', models.PositiveIntegerField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='captable.security')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='captable.stakeholder')),
            ],
        ),
    ]
