# Generated by Django 5.2.4 on 2025-08-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitchdeck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pitchdeckanalysis',
            name='analysis_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pitchdeckanalysis',
            name='chart_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pitchdeckanalysis',
            name='ratings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
