# Generated by Django 5.2.4 on 2025-08-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='admin_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='requires_document',
            field=models.BooleanField(default=False),
        ),
    ]
