# Generated by Django 5.2.4 on 2026-02-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_admin_checked_task_requires_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='company_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], max_length=50),
        ),
    ]
